/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {

        all (uri : "/**"){
            before = {
                 if(!controllerName) return true
                 accessControl(){true}
            }
        }
    }
}
